# This is for testing `actions-workflows` itself.

name: CI

on: [ push, pull_request ]

jobs:
  repo-guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
      - run: ./script/github-actions-repo-guard.ts

  lint:
    needs: repo-guard
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
      - run: make setup
      - run: make lint

  fish:
    needs: repo-guard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: ls /home/runner/work/actions-workflows/actions-workflows/.github/workflows/
      - uses: ./actions/install-fish
      - run: fish --version
